### ISSUE TITLE
Add a script to reindex files or change how we id

### ISSUE THREAD

**Issue by bagelbits** [5e-bits/5e-database#121]
This would probably be an all or nothing script as it would need to reindex associations as well.

Alternatively, we could set ids to not be sequential numbers. Instead have them be something random. Something akin to a UUID comes to mind. This would avoid needing to reindex ever again. But there needs to be a standard way to generate a new id.

@ogregoire @Alex-frazer Thoughts?

**Comment by bagelbits** [comment]
This is coming off of a short discussion here: https://github.com/adrpadua/5e-database/pull/119

**Comment by ogregoire** [comment]
For id, I'd just use the name and normalize it with regexes, like this:

1. Use the language's "to lowercase" function.
2. Delete unwanted characters such as initial and final whitespaces, as well as apostrophes inside words: `(?:(?<=\bo)'|'(?=s\b)|^\W+|\W+$)`
3. Replace sequences of non letters with a single dash: `\W+` to `-`.

This has the advantage to be deterministic and usually unique because, in the SRD, names are unique.

I think regexes are a good fit because they can be used in any language so no matter the scripting language, it will just work. Also, those regex can be simplified or aggregated, but I haven't found a single regex to do all that at once.

**Comment by bagelbits** [comment]
I think that's a reasonable ID pattern.

**Comment by bagelbits** [comment]
So that would convert `Arcanist's Magic Aura` into `arcanists-magic-aura`. Yeah. I definitely like that.

**Comment by bagelbits** [comment]
I just hope that doesn't break anything for anyone.

**Comment by ogregoire** [comment]
> I just hope that doesn't break anything for anyone.

That will definitely break something for someone. But keeping changing the ids because we remove or add stuff will also definitely break something for someone.

The change will break everything for everyone, but after that nothing will break for no one.

**Comment by bagelbits** [comment]
If we're going to do this, we may as well drop the domain from the URL as well.

**Comment by bagelbits** [comment]
Actually, that would be a pretty good use for a repository tag. Since essentially that would be a major version change.

**Comment by bagelbits** [comment]
@ogregoire If you want to pull the trigger on this, feel free to. I think I'm about to have my hands full.

**Comment by bagelbits** [comment]
I added a PR to address #113 which drops the domain from the URLs.

**Comment by bagelbits** [comment]
I also started throwing together a script to do the  ID conversion.

**Comment by bagelbits** [comment]
Well. That might do it but I probably messed something up.

**Comment by bagelbits** [comment]
Okay. I think this PR is in a good state for adding string ids.
