### ISSUE TITLE
Spell List Question

### ISSUE THREAD

**Issue by Slusks** [5e-bits/5e-database#162]
I'm trying to make a random spell generator using your API and this list of spells (http://dnd5e.wikidot.com/spells). It looks like some of the spells on that list aren't in your database. I was curious where you got your spell list from and/or if there was a possibility you were going to update it.

Thanks for making this though!

**Comment by ogregoire** [comment]
@Slusks The spell list comes from the [Systems Reference Document](https://dnd.wizards.com/articles/features/systems-reference-document-srd) (SRD), a document that we can freely reuse and implement in API without risking any copyright infringement. The SRD contains nearly all spells of the Player's Handbook (PHB), but not all. Also, some spells are renamed between the two documents: for instance, "Tasha's hideous laughter" in the PHB is renamed as "Hideous laughter" in the SRD.

What you're linking is a list of spells that are contained in the PHB, and other sources even unofficial ones like Unearthed Arcana. Copying them without permission from Wizards of the Coast (WotC) is a copyright infringement.

We do not have the permission from WotC to include all the spells so we're limiting ourselves to those found in the SRD.

We will not add the spells you mention that are not in the SRD, and we will not accept any pull request that contains those spells because we do not want this API to infrige WotC's copyright.

I'm closing this issue as we won't do anything about it, but if you have more questions, feel free to ask.

**Comment by Slusks** [comment]
Thank you for the update! I am new to 5e and so I did not fully understand the copyright implications. Thank you for explaining.
