### ISSUE TITLE
Data:  Drow Innate Spells Darkness / Faerie Fire showing wrong Usage

### ISSUE THREAD

**Issue by Illydth** [5e-bits/5e-database#213]
If I don't miss my guess, the data for the drow elf is incorrect.

Under it's innate spell casting abilities, faerie fire is listed at 3 times / day while darkness is listed at 72 times / day.

Both innate abilities are listed as 1 time / day usage on the SRD.

https://www.5esrd.com/gamemastering/monsters-foes/monsters-by-type/humanoids/elf/elf-drow/

**Comment by ogregoire** [comment]
Thank you for the reporting! The fix is merged in this repo.

However, please don't use that link for future references. They may also have issues, although less since they don't dataify the SRD: they only format it. The only official source is the PDF present here: https://dnd.wizards.com/articles/features/systems-reference-document-srd

**Comment by Illydth** [comment]
Wasn't even aware that document existed.  Thank you for the pointer!

**Comment by ogregoire** [comment]
> Wasn't even aware that document existed. Thank you for the pointer!

Thank *you* for noticing the issue! ;)
