### ISSUE TITLE
Inconsistent StartingEquipment Schema

### ISSUE THREAD

**Issue by markbastian** [5e-bits/5e-database#274]
The StartingEquipment json has some inconsistencies, such as:

```
      {
        "choose": 1,
        "type": "equipment",
        "from": [
          {
            "equipment": {
              "index": "shortsword",
              "name": "Shortsword",
              "url": "/api/equipment/shortsword"
            },
            "quantity": 1
          },
          [
            {
              "equipment": {
                "index": "shortbow",
                "name": "Shortbow",
                "url": "/api/equipment/shortbow"
              },
              "quantity": 1
            },
            {
              "equipment": {
                "index": "arrow",
                "name": "Arrow",
                "url": "/api/equipment/arrow"
              },
              "quantity": 20
            }
          ]
        ]
      }
```

In this case the options are an object and a list of objects. In other areas, there's an "equipment_option" tag. I'd suggest:

```
      {
        "choose": 1,
        "type": "equipment",
        "from": [
          {
            "equipment_option": [{
              "equipment": {
                "index": "shortsword",
                "name": "Shortsword",
                "url": "/api/equipment/shortsword"
              },
              "quantity": 1
            }]
          },
          {
            "equipment_option": [
              {
                "equipment": {
                  "index": "shortbow",
                  "name": "Shortbow",
                  "url": "/api/equipment/shortbow"
                },
                "quantity": 1
              },
              {
                "equipment": {
                  "index": "arrow",
                  "name": "Arrow",
                  "url": "/api/equipment/arrow"
                },
                "quantity": 20
              }
            ]
          }
        ]
      }
```

In all cases, your options are equipment_options and you get a list of equipment in each (even if the list contains one item). In the final character sheet, your equipment is going to be a concatenation of all of these items, so lists should be ok.

**Comment by fergcb** [comment]
The `equipment_option` attribute wraps a nested Choice structure in a `from` array. You *should* find this is consistent thoughout.

I think there's a case, however, for unwrapping nested Choice structures from `equipment_option`, as the structure is easily identifiable on its own.

I recommend joining the Discord server, if you haven't already, because the structure of the StartingEquipment documents is something we have discussed a lot in the past, and that we often revisit.

Also, in the near future, we'll be updating the documentation for Choices and StartingEquipment to better explain the structure, and why it is the way it is.

**Comment by markbastian** [comment]
Sounds good. I'll join up. I've just discovered this project and it is pretty awesome. Thanks!

**Comment by fergcb** [comment]
I had some free time, so I've put together some of the ideas that have been bouncing around the repos and the Discord server into something a bit more tangible. I've defined a proposed structure in TS syntax, and provided an example of the structure in the form of the Fighter's `starting_equipment_options` array (while we're here, would `starting_equipment_choices` be a better name, given that it's an array of `Choice` structures?).

The biggest issue being addressed is **consistency**. A lot of data consumers don't like arrays with items of mixed types. The proposal uses inheritance to give all items in an array a common type, indicated by a `type` property for easy deserialization.

Another enhancement is the inclusion of a `desc` string for Choices, so that consumers don't have to write any funky algorithms to tell a human user what they're choosing from.

One flaw right now is that equipment categories don't have the same structure as ResourceLists. For now, the proposal ignores this. It might be more elegant than further complicating the Choice structure, to just have a way to fetch an equipment category's items as a ResourceList.

Here's the gist: https://gist.github.com/fergcb/a02760c460def3904358cbdfea9312c6

This is by no means a final draft - more just an attempt to get the ball rolling on cleaning Choices up!

**Comment by ogregoire** [comment]
What is the difference between an array and a list?

**Comment by fergcb** [comment]
An OptionSet with a `type` of `"reference_list"` means the choice is from a ReferenceList (as in the docs). A type of `"array"` means the choice is between a literal array of Options.

**Comment by ogregoire** [comment]
Well, it's unclear. People associate lists with arrays and arrays with lists. In many languages, arrays are the same as lists and lists are arrays. If we want to differenciate between a reference list and an option list, why not just call them `"reference_list"` and `"option_list"`?

Personally, I fully parse the data in Java. I don't check what the .ts is, I just read the .json and make sure I adapt my model to it at every change.

I believe that if we let the .ts file dominate, we'll make the data too linked to a language and not clear enough in itself. I believe the data should be clear and make sense on its own, rather than within any external context.

After that, people can try to make sense of it and create the .ts files, but I believe that the .ts file should be there as a helper, not as the design.

So in the sake of inclusiveness, I'm not in favor of using both the words `"array"` and `"list"`.

**Comment by fergcb** [comment]
> If we want to differenciate between a reference list and an option list, why not just call them "reference_list" and "option_list"

The two are not only semantically different, they also differ in structure. The `type` property of an OptionSet tells the consumer what kind of structure contains the available options: either a plain JSON array of Options, or a ReferenceList (an existing structure in the API, *not* a JSON array). Hence, I chose the strings "reference_list" and "array".

These names accurately describe, in established terms, the structure of the data. I would be concerned that using the same pattern for both, e.g. "reference_list" and "option_list", would evoke the notion that the two structures are similar, e.g. an array of References or an array of Options, respectively. This is not the case.

> I believe that if we let the .ts file dominate, we'll make the data too linked to a language and not clear enough in itself. I believe the data should be clear and make sense on its own, rather than within any external context.

The TS code here is simply aiming to put across my first rough draft for the proposed structure - to get it "on paper" somewhere rather than as a cloud of disconnected ideas over two repositories and a Discord server. **It is not user-facing documentation**, and it is not intended to be. I understand that it may not be ideal for any contributors who are only here to make edits to the JSON files directly. However, it is an easy way to note down these ideas, and is somewhere between the JSON used here and the Mongoose schemas in the API repository. In addition, @bagelbits has mentioned an interest in porting the project to TypeScript at some point, so I was playing into this somewhat.

> So in the sake of inclusiveness, I'm not in favor of using both the words "array" and "list".

In most cases I'd agree, when talking about arrays, it's nice to keep the terminology simple and choose one or the other. This isn't what's happening here. "array" and "list" don't only come with different semantics, here, but different structures. In the case of "resource_list" especially, these are meanings that are already established in the documentation. I don't think there's much sense in using the same word twice for two different things.

**Comment by bagelbits** [comment]
To be clear, the TS I'm proposing is purely the server code for the API and touches nothing in this repo.

I'll take a look at your gist a little later.

**Comment by fergcb** [comment]
RE: TS in the API, I figured as much. But hey, you said you could use the practice ;)

I figured the syntax is fairly straightforward: key-value pairs of `name: Type`, and far easier to put together than markdown tables or full HTML docs.

Also, to be completely transparent, my TS wrapper for the API is fully typed this way, so it's become the natural way for me to express the structure of the data in this API. It also allows the JSON to be validated against the schema inside VSCode, which is a bonus.

**Comment by ogregoire** [comment]
If we name an array as `reference_list`, we should also name the other arrays with similar names. So you give a specific name to one, but a generic one to another. I disagree with that approach.

The fact that they're already established and documented doesn't make those names far distinct enough.

As I said, the documentation is here to support the data, not the other way around. So if there are confusing things in the data (and the usage of both `array` and `list` is one of those confusing things), it should be clarified in the data, and the documentation should be adapted.

[Naming things is hard](https://martinfowler.com/bliki/TwoHardThings.html), I know.

Now that I established this, I actually suggest to rename that "resource_list" to "reference", because that's what it is: a reference.

Also, I find the names "single", "list" to be bad. I'll try to think about those names.

**Comment by GeraldTo** [comment]
It might be better to have the single objects be the same structure as the list objects. I basically mean it should be a list under item instead of a single object and instead have a count attribute along with it. They'll all be structured the same in this way.

**Comment by ogregoire** [comment]
Also, for "array", I'd rather have a name like "options". Yes it calls back from the general name (trait_options, starting_equipment_options), but that's what it really is: an area of options, therefore options.

**Comment by fergcb** [comment]
> If we name an array as reference_list, we should also name the other arrays with similar names.

Once again, ReferenceLists are not arrays.

**Comment by fergcb** [comment]
> Also, for "array", I'd rather have a name like "options". Yes it calls back from the general name (trait_options, starting_equipment_options), but that's what it really is: an area of options, therefore options.

Unlike attribute names like "trait_options" (which I'd argue would be better named "choices", not "options", as they're arrays of choices to be made, not the available options - but that's a separate issue), the `type` attribute here refers more specifically to the structure of the data, rather than its role. For example, both a ReferenceList and an Array of Options are methods of representing available options. `type` only serves to tell us which method is being used.

**Comment by fergcb** [comment]
> It might be better to have the single objects be the same structure as the list objects. I basically mean it should be a list under item instead of a single object and instead have a count attribute along with it. They'll all be structured the same in this way. 

@GeraldTo, You mean have single items and sets of items (e.g. "chain mail" vs. "leather armor, a longbow and 20 arrows") both being "list" types, one with a single item and one with three? That's a reasonable suggestion.

That said, I'm not sure it's actually feasible given that `list` types can include single items *and* choices. Therefore, they must contain an array of Options, not simply (quantitied) APIReferences. If there is no "single" type, how do we represent a terminal item in the structure? It'd be lists all the way down. Perhaps I'm missing an obvious solution.

My main motive in keeping them separate was to conserve the semantics of the SRD as the single source of truth, but I can see the value in sacrificing that for simplicity's sake, if there is indeed a nice solution. I'm all ears!

Nested choices must remain a separate type as they have a fundamentally different structure. All the complexities and annoyances seem to trace back to nested choices!

**Comment by fergcb** [comment]
@ogregoire, just to be clear, I am not at all adverse to changing the strings used to differentiate the `type`s in this structure; if you can offer some suitable alternatives, that'd be great!

**Comment by ogregoire** [comment]
> which I'd argue would be better named "choices", not "options", as they're arrays of choices to be made, not the available options

Options are things that are presented to you. Choice is the decision you take among the options. It's a different point of view. [See this explanation.](https://boringbug.com/2017/11/15/the-difference-between-options-and-choices/) And it's that definition that we use here. How is it incorrect? If at all, we should change "choice" to "option" rather than the other way around. When the SRD present the various possibilities, it lays out the options it offers to you, not the choices it offers to you. But you make a choice out out the options in front of you.

> the type attribute here refers more specifically to the structure of the data, rather than its role

Well, I believe that it's an error to name things on the structure rather than on the role or a description. It's like if in TS (since you seem to know that language), you name everything as "array", "reference" or "pointer" because that's the structure used in a memory instead of "train", "boat" or "book". If you do that, people will be lost. Me the first. One should never name things after how they are represented in a programming language: they should be named about how the business uses it. Every book, from Clean Code to The Pragmatic Programmer will tell you that.

`"resource_list"` represents indeed not an array, but it's a pointer, a reference to an array. So in the end, the business value there *is* an array.

**Comment by fergcb** [comment]
So far, we've only been addressing the OptionSet structure - the one in the `from` field of the Choice.

Upon picking this apart, I can see that the `"single" | "list" | "choice"` types for the Option structure itself perhaps aren't optimal. Certainly `array` would be more appropriate than `list`. I was hoping that `list` would package the semantics of the "chooser" receiving *all* of the items in the list, but I can see how it would cause confusion as it does simply bubble down to being an array of Options, just like the `array` type of OptionSet.

I'm more happy with `single`, and I can't think of a better alternative - maybe `item` or something indicating that it is an APIReference with a quantity (it corresponds to the `{ count: number, of: APIReference }` structure). I'm most comfortable with `choice`. It corresponds directly to the Choice structure.

**Comment by bagelbits** [comment]
Closing this in favor of #383 since that is handling the general Choice reforms.
