### ISSUE TITLE
Missing Dissonant Whispers spell?

### ISSUE THREAD

**Issue by unRARed** [5e-bits/5e-database#298]
pg. 234 PHB

**Comment by bagelbits** [comment]
Unfortunately, Dissonant Whispers is not in the SRD.

### Read this Before Entering an Issue

The data provided in this API is limited to what is included in the [Open Gaming License (OGL) following the Systems Reference Document (SRD) requirements](https://dnd.wizards.com/articles/features/systems-reference-document-srd).  

Many subraces, spells, magic items, monsters, etc. are not included and for legal reasons **can not** be added to this free API.

### SRD 5.1 FAQ
**Why does the SRD only have one background and one feat? Why do the PC races not include all of the subraces?** The goal of the SRD is to allow users to create new content, not to replicate the text of the whole game. We encourage players, DMs, and publishers to come up with their own backgrounds and feats.

**Why is the SRD missing some spells, magic items, and monsters?** In general, the criteria for what went into the SRD is if it (1) was in the 3E SRD, (2) has an equivalent in 5th edition D&D, and (3) is vital to how a class, magic item, or monster works. For example, the 3E SRD has the delay poison spell, but in 5th edition that's handled by the protection from poison spell, so protection from poison is in the SRD.

**Comment by unRARed** [comment]
Ahh bummer, so not possible to even reference vaguely with "GOTO pg 234"? As this website is doing: https://www.dandwiki.com/wiki/5e_SRD:Dissonant_Whispers

**Comment by txtsd** [comment]
Unfortunately not.

**Comment by ogregoire** [comment]
We don't want to maintain the huge amount of data that comes with each new book. If today we miss a spell, tomorrow we miss a monster and then we're down in the rabbit hole, maintaining all the books.

The work is already hard enough with only the SRD. If you believe that you can get away with "see page X", you could fork this repo and provide whatever data you wish.

We're going to keep the SRD as our only basis. We even removed the PHB/DMG pages that were previously mentioned because they're not SRD data, so we're definitely and consciously away from that kind of integration.
