### ISSUE TITLE
proficiency_choices order

### ISSUE THREAD

**Issue by GeraldTo** [5e-bits/5e-database#355]
under each classes/[index] there's an object called proficiency_choices which holds an array of proficiency objects. In every one of the classes the skill proficiencies is the first index of the array except for monk which is at index 2. I believe for consistency with the other classes it should be the first index. Also This is just a suggestion but maybe add a name attribute at each imdex to label the type of proficiency_choices it is (i.e. skills or instruments)

**Comment by ogregoire** [comment]
Counter-argument: they're in the correct order since they're in the order defined in the SRD.

Though the bard proficiencies are in the wrong order and should be reverted.

**Comment by GeraldTo** [comment]
> Counter-argument: they're in the correct order since they're in the order defined in the SRD.
> 
> Though the bard proficiencies are in the wrong order and should be reverted.

I do believe that is valid.  I just assumed the Bard proficiencies were in order. However I still think proficiency_choices for the monk is wrong since the SRD defines the tools choices being choose one type of artisan’s tools or one musical instrument not both.

**Comment by ogregoire** [comment]
> Also This is just a suggestion but maybe add a name attribute at each imdex to label the type of proficiency_choices it is (i.e. skills or instruments)

I'm actually against it, for two reasons:

* Firstly the SRD doesn't specify the difference between the various types of proficiencies (skills, tools, weapons and armors, while instrument is a subtype of tool).
* Secondly, if we were to require such a field, custom extensions allowing swapping between the proficiency types would be hard to put in place. See *Tasha's Cauldron of Everything* which, without spoiling much, allows swapping between a tool proficiency and a simple weapon proficiency at character creation. This indirectly blurs the category types that you want to add.

**Comment by fergcb** [comment]
> Firstly the SRD doesn't specify the difference between the various types of proficiencies (skills, tools, weapons and armors, while instrument is a subtype of tool).

The SRD does actually explain how different proficiencies work. While most/all of them boil down to "add your proficiency score if you're proficient", different proficiencies are triggered for different events. E.g. weapon proficiencies apply for attack rolls, skills for skill-based ability checks, tools for only very specific ability checks. The difference is subtle, but I can see the value for data consumers in acknowledging the difference. _That said_, the difference is already apparent from the `type` attribute of the proficiency object itself.

However, I can also see the value in having a human-readable description for the Choice object, so that the consumer doesn't have to implement some funky algorithm to figure out how to present the choice to the user. Like so:

```json
{
  "desc": "one type of artisan's tools or one musical instrument",
  "choose": 1,
  "type": "proficiencies",
  "from": [
    {
      "desc": "one type of artisan's tools",
      "choose": 1,
      "type": "proficiencies",
      "from": [
        {
          "index": "alchemists-supplies",
          "name": "Alchemist's supplies",
          "url": "/api/proficiencies/alchemists-supplies"
        },
        ...
      ]
    },
    {
      "desc": "one musical instrument",
      "choose": 1,
      "type": "proficiencies",
      "from": [
        {
          "index": "bagpipes",
          "name": "Bagpipes",
          "url": "/api/proficiencies/bagpipes"
        },
        ...
      ]
    },
  ]
}
```

This is one of many improvements to Choice structures we've been talking about for some time, and it's something that I'd really like to get sorted, if it weren't for my profound lack of free time at the moment. Perhaps it's worth me opening a meta issue to track the various future enhancements.

**Comment by bagelbits** [comment]
Gonna close this out following choice reform landing.
