### ISSUE TITLE
Fiend subclass spell prerequisites seem off

### ISSUE THREAD

**Issue by SleeplessOne1917** [5e-bits/5e-database#424]
While looking at the subclass spells, I noticed that all of the prerequisites for the fiend subclass reference warlock level 1. This doesn't seem correct. I'll be using information from the [Roll20 Compendium page on the warlock](https://roll20.net/compendium/dnd5e/Classes:Warlock?expansion=0#h-The%20Fiend) to show you what I mean.

The table for the fiend spells is the following:
|Spell Levels | Spells |
|-------------|--------|
| 1st| Burning Hands, Command|
| 2nd| Blindness/Deafness, Scorching Ray|
| 3rd| Fireball, Stinking Cloud|
| 4th| Fire Shield, Wall of Fire|
| 5th | Flame Strike, Hallow |

Also worth pointing out is the compendium's entry on spells known of first level or higher.

> You learn a new Warlock spell every time you gain a level from 2 through 9, as well as at level 19. **A spell you choose must be of a level no higher than what's shown in the table's Slot Level column for your level.** When you reach 6th level, for example, you learn a new Warlock spell, which can be 1st, 2nd, or 3rd Level.

Looking at these two pieces of information, it doesn't seem to make sense making all of the fiend pact's spells prerequisite's level 1. That would mean, for example, that a player could use Flame Strike, a 5th level spell, when they only have 1st level spell slots available.

I propose that the prerequisite levels be changed to match when the warlock will have slots for a given spell.

**Comment by bagelbits** [comment]
I think that's a reasonable proposal. Feel free to cut a PR to address it!

**Comment by ogregoire** [comment]
There are no prerequisites for those spells. The spell level is an indication, and there shouldn't be any prerequisites because the data don't directly say there is any. Basically, all this feature does is adding the spells to the character's available warlock spell lists.

To me, the good call would be to remove the prerequisites field entirely and make it optional.

The spell prerequisite levels are handled in the spells file itself.

**Comment by bagelbits** [comment]
This proposed change is for the Warlock level that the spell becomes available at.

**Comment by fergcb** [comment]
> make it optional

It already is optional, in the sense that the consumer can ignore it if they want to.

However, if they're making a character sheet builder or similar, I think it could be really useful to know the level at which the spells become available to the character** (i.e. when the Warlock's spell slot level is high enough), so that the spells are only added to the sheet when they're usable. But again, it's just an optional thing for the consumer to use if they want to do it that way - they don't have to.

** ETA: without having to check each individual spell

**Comment by ogregoire** [comment]
A naive implementation would show two prerequisites: the one from the spell and the one from the subclass. And they'd be the same, and the developer would have to check every field and map logic to check that they're indeed equivalent. And in some languages it can be hard. And then only the can decide it's optional.

There are no prerequisites in the description of the subclass, there shouldn't be any in the corresponding data.

It's better for the data as it doesn't spread requirements, especially useless ones, as a burden to the developer.

**Comment by SleeplessOne1917** [comment]
I've thought about this a bit, and I think there's a good argument for there being no prerequisites. I'll repeat the rule for warlocks learning new spells:
> You learn a new Warlock spell every time you gain a level from 2 through 9, as well as at level 19. **A spell you choose must be of a level no higher than what's shown in the table's Slot Level column for your level.** When you reach 6th level, for example, you learn a new Warlock spell, which can be 1st, 2nd, or 3rd Level.

If we take @fergcb's example where someone's making a character sheet builder, they'll likely already have logic for handling which spells are available to learn at a given level. After all, the subclass spells aren't the only spells that will be available to learn: they'll also have to apply that logic to the rest of the warlock's spell list. It would make more sense for the maker of the character sheet builder to use the same logic for both the class and subclass spells than for subclass spells to be special.

**Comment by ogregoire** [comment]
Also, if we take the logic of "must be warlock level X", and we extend it to everything (because we should if we are consistent), then they all have this prerequisite and what happens? Features that say "take a spell from another spell list" don't work anymore. So let's just get rid of these prerequisites, they're useless at best and a blocker at worst.

**Comment by bagelbits** [comment]
Should I reopen this issue or make a new one?
