### ISSUE TITLE
Problems with Gnome & Elf subraces

### ISSUE THREAD

**Issue by ashvin-umaharan** [5e-bits/5e-database#70]
The Gnome _subraces_ (**Forest Gnome** and **Rock Gnome**) with links [http://www.dnd5eapi.co/api/subraces/7](http://www.dnd5eapi.co/api/subraces/7) and [http://www.dnd5eapi.co/api/subraces/8](http://www.dnd5eapi.co/api/subraces/8) respectively, return "null".

The Elf _subraces_ **Wood Elf** and **Dark Elf (Drow)** with links [http://www.dnd5eapi.co/api/subraces/5](http://www.dnd5eapi.co/api/subraces/5) and [http://www.dnd5eapi.co/api/subraces/6](http://www.dnd5eapi.co/api/subraces/6) respectively, are not listed under `subraces` property of Elf _race_ ([http://www.dnd5eapi.co/api/races/2](http://www.dnd5eapi.co/api/races/2)). 

Please fix.

**Comment by ogregoire** [comment]
The subraces present in the SRD are the following:

* Hill Dwarf
* High Elf
* Lightfoot
* Rock Gnome

Any other subrace shouldn't be present in the API since the API only uses the SRD to be compliant with OGL.

So the fix would be to review both the races and subraces files to fix the usage, mostly by removing the subraces not present in the SRD.

**Comment by bagelbits** [comment]
@ogregoire is correct in this. I've been meaning to clean up the subraces that aren't in SRD. Thank you for taking point on this.
